### ISSUE TITLE
Use of unicode encoding in ncursesFM

### ISSUE THREAD

**Issue by JujuLand** [FedeDP/ncursesFM#7] opened 2016-05-11 06:28 UTC
Hi, 

just as asked in another thread, use unicode in ncursesFM to avoid trash display of accentued letters, and perhaps allos to display help in locale language.

Thanks
A+

**Comment by FedeDP** [comment] 2016-05-16 19:50
Hi!
Can you let me know what is your locale? Because i have no issues at displaying accentued chars.
This way i can test your configuration :)
Thanks!

**Comment by JujuLand** [comment] 2016-05-16 21:03
```
Le 16/05/2016 21:50, Federico a écrit :


  Hi!
    Can you let me know what is your locale? Because i have no
    issues at displaying accentued chars.
    This way i can test your configuration :)
    Thanks!

French

Thanks
A+
-- 

  Alain Aupeix
  http://jujuland.pagesperso-orange.fr/
  http://pissobi-lacassagne.pagesperso-orange.fr/

  U.buntu 12.04 | G.ramps 3.4.9-1 | H.arbour 3.2.0dev
    (2016-04-20 16:03) | Hw.Gui 2.19-6 (2533)
```

**Comment by FedeDP** [comment] 2016-05-16 21:08
What's the output of 
echo $LANG
?
Thanks for your time!

**Comment by JujuLand** [comment] 2016-05-17 06:26
```
Le 16/05/2016 23:08, Federico a écrit :

  What's the output of 
    echo $LANG

alain@Gramps-JujuLand:~$ echo $LANG
fr_FR.UTF-8

A+
-- 


  Alain Aupeix
  http://jujuland.pagesperso-orange.fr/
  http://pissobi-lacassagne.pagesperso-orange.fr/

  U.buntu 12.04 | G.ramps 3.4.9-1 | H.arbour 3.2.0dev
    (2016-04-20 16:03) | Hw.Gui 2.19-6 (2533)
```

**Comment by JujuLand** [comment] 2016-05-17 10:41
Hi, thinking you have modified something, I have pull the source, and now I have errors when making:

Package ncursesw was not found in the pkg-config search path.
Perhaps you should add the directory containing `ncursesw.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ncursesw' found
cd src/; cc -o ../ncursesFM *.o -lpthread  -lX11   -lconfig    -lcups
archiver.o: In function`create_archive':
archiver.c:(.text+0x5): undefined reference to `archive_write_new'
archiver.c:(.text+0x1b): undefined reference to`archive_write_add_filter_gzip'
archiver.c:(.text+0x2f): undefined reference to `archive_write_set_format_pax_restricted'
archiver.c:(.text+0x54): undefined reference to`archive_write_open_filename'
....
alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ sudo apt-get install ncursesw
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances  
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet ncursesw

alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ sudo apt-get install ncursesw-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances  
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet ncursesw-dev

alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ dpkg -l | grep curses
ii  libncurses5                                   5.9-4                                               shared libraries for terminal handling
ii  libncurses5:i386                              5.9-4                                               shared libraries for terminal handling
ii  libncurses5-dev                               5.9-4                                               developer's libraries for ncurses
ii  libncursesw5                                  5.9-4                                               shared libraries for terminal handling (wide character support)
ii  libncursesw5:i386                             5.9-4                                               shared libraries for terminal handling (wide character support)
ii  mtr-tiny                                      0.80-1ubuntu1                                       Full screen ncurses traceroute tool
ii  ncurses-base                                  5.9-4                                               basic terminal type definitions
ii  ncurses-bin                                   5.9-4                                               terminal-related programs and man pages

A+

**Comment by FedeDP** [comment] 2016-05-17 11:04
Have you got libncursesw5-dev installed?(note the 'w')
From your previous output it seems you're missing that (and this would explain trash chars too).
The only issue left with unicode support is catching unicode stringa entered by user and print them(eg while creating new file).

**Comment by JujuLand** [comment] 2016-05-17 11:27
Yes it was the reason.
How can have miss it ? /:)

utf-8 is now ok.
Thanks

Just about help zone.
Could it be apart of c source to allow easily to translate it, without having to modify code ?
Perhaps by using po/mo file ?

A+

**Comment by FedeDP** [comment] 2016-05-17 15:07
Yes, i'll look into that as soon as unicode support is completed :)
Again, if you don't mind, can you open a feature request? This helps me to keep track of every issue.
Really thanks for your time!

**Comment by FedeDP** [comment] 2016-05-18 18:44
Hi @JujuLand . I just committed unicode support! (image_previewer branch...i should _really_ have called it "develop" branch...)
Can you test it?
Eg: create a new file with unicode chars, and now everything should be ok.
Let me know if everything's fine :)
Thanks!

**Comment by JujuLand** [comment] 2016-05-18 19:19
Humm ...
I have pull, and build, but I'm not sure that I have the last version ( it seems to be dated of May 17 th.
Am-i right ?
What are you talking about creating a new unicode file ?
I don't understand what you want.

For now, the files or folders using accentued namefile are correctly displayed.
Is-it what you want to know ?

A+

**Comment by FedeDP** [comment] 2016-05-18 19:43
git pull
git checkout image_previewer
make
./ncursesFM

thanks :)
What i meant is: when you're inside ncursesFM, try to create a new file with a name that contains unicode chars (eg: èçùà+èef) and let me know if it is displayed correctly!

**Comment by JujuLand** [comment] 2016-05-18 20:12
```
Le 18/05/2016 21:43, Federico a écrit :


  git pull
    git checkout image_previewer
    make
    ./ncursesFM

ok

  try to create a new file with a name that contains unicode
    chars (eg: èçùà+èef) and let me know if it is displayed
    correctly! 

'n' => Insert new name:   impossible to enter accentued letters
:(

A+
-- 

  Alain Aupeix
  http://jujuland.pagesperso-orange.fr/
  http://pissobi-lacassagne.pagesperso-orange.fr/

  U.buntu 12.04 | G.ramps 3.4.9-1 | H.arbour 3.2.0dev
    (2016-04-20 16:03) | Hw.Gui 2.19-6 (2533)
```

**Comment by FedeDP** [comment] 2016-05-18 20:15
That's really weird...
What's the output of:
ldd ./ncursesFM | grep ncurses
?

**Comment by JujuLand** [comment] 2016-05-18 20:20
ldd ./ncursesFM | grep ncurses
    libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007fa8a3b2a000)

A+

**Comment by JujuLand** [comment] 2016-05-18 20:21
ii  libncurses5                                   5.9-4                                               shared libraries for terminal handling
ii  libncurses5:i386                              5.9-4                                               shared libraries for terminal handling
ii  libncurses5-dev                               5.9-4                                               developer's libraries for ncurses
ii  libncursesw5                                  5.9-4                                               shared libraries for terminal handling (wide character support)
ii  libncursesw5:i386                             5.9-4                                               shared libraries for terminal handling (wide character support)
ii  libncursesw5-dev                              5.9-4                                               dev

**Comment by FedeDP** [comment] 2016-05-18 20:26
Are you sure you're running ncursesFM from within the image_previewer branch (and not from your globally installed version?)
./ncursesFM
instead of:
ncursesFM

**Comment by JujuLand** [comment] 2016-05-18 20:41
I was sure, but, as I had previously modified string_constants.c, I suppose I haven't pay attention to the message, and in fact I use the master branch.
I have removed the folder, clone again, checkout, and make, and it's now ok, accentued chararcters are accepted in the name.
But, unfortunately, there is a new bug concerning backspace which gives a cwith an accent instead of remove the character. problem with left, right, up and down keys :(

A+

**Comment by JujuLand** [comment] 2016-05-18 20:43
Another problem concerning filename editing : it's not possible to escape the creation. Ennoying !

A+

**Comment by FedeDP** [comment] 2016-05-18 21:27
I just pushed a new version with arrow keys fixed.
I don't understand your issue with backspace...i cannot reproduce that.

To escape the creation you've got to delete all entered name, and press enter (with an empty name). I'm gonna rework this, and may be i'll switch to ESC to quit ncursesfm/leave input mode.

**Comment by JujuLand** [comment] 2016-05-19 06:27
```
Le 18/05/2016 23:27, Federico a écrit :


  I just pushed a new version with arrow keys fixed.


Well, no more problem, but I thought left and right ought to have an
action to move the position over the already entered letters. it
would be necessary to set cursor on when editing.


    I don't understand your issue with backspace...i cannot
    reproduce that.

https://www.dropbox.com/s/fix5803guvjlzog/backspace.png?dl=1

On the hardcopy, you can see this kind of c with a sort of accent.
These are backspace effects.

  To escape the creation you've got to delete all entered name,
    and press enter (with an empty name).

Yes, but it's impossible with the backspace bug.

   I'm gonna rework this, and may be i'll switch to ESC to quit
    ncursesfm/leave input mode.

It would be nicer.

Thanks
A+
```

**Comment by FedeDP** [comment] 2016-05-19 14:31
Mmh about backspace, my only guess is our two terminals/locales/keyboard (never understood whom that's up to) encodes backspace with different codes.
I should have fixed that, but before pushing to github i want to fix arrow keys to move inside input string. You're right saying that left/right arrows should move the cursor, and i'll implement that asap.

On my local repo, i've fixed ESC key to leave current mode/program/input mode too, so you'll be able to press ESC to escape a question.

So, a soon as i fix arrow keys, i'll push and let you know.

Thanks for your help testing this out!

**Comment by FedeDP** [comment] 2016-05-21 16:29
Ok every issue should now be gone (on image_previewer branch).
- ESC to leave ncursesFM + leave current mode/input mode.
- added support for arrow keys right/left in input mode
- added support for del button in input mode
- i think i've fixed your issue with backspace.  
  Let me know if everything's ok :)
  Thanks for the testing!

**Comment by JujuLand** [comment] 2016-05-21 17:15
Nice all or about is working nicelly.

Just a very little detail,thinking it was possible to change keyboard mode, I hit Insert tochange from insert to overwrite, and the opposite.
It doesn't work, and only insert mode is avalaible. It inserts a character (a kind of n minuscule with the a kind of queue)
If you don't think it's necessary to be able to use overwrite mode, as it's possible and better to be in insert mode, just disable the insert key.

Else, Esc works ok

A+

**Comment by FedeDP** [comment] 2016-05-21 17:53
You're right, i didn't even think about that. 
Implemented now :)

Thank you very much!

**Comment by JujuLand** [comment] 2016-05-21 18:50
You have just now to block home, end, PgUp and PgDn ;)

A+

**Comment by JujuLand** [comment] 2016-05-21 18:53
Some things missing:

Adding a version to now what we use (for example at the right end of the help box
Exemple:
................................... |
--- ncursesFM v1.05 --+

And also the possibility to hide 'No Power supply info avalaible', not really interesting on a desktop computer.

Thanks
A+

**Comment by FedeDP** [comment] 2016-05-22 09:36
Fixed home/end (they will move cursor to start/end of input), and blocked PG_UP/DOWN (thanks!!).  
Added a version on helper title + more detailed info on "--help" switch (ncursesFM --help).  
You already can hide whatever you wish from latest line, have a look at ncursesFM.conf (last line): you can customize order/what to show of sysinfo line.

Only issue remaining is that version is set to 2.2 instead of 3.0 (latest). I don't understand why, may be i tagged that release in a wrong way?

**Comment by JujuLand** [comment] 2016-05-22 17:02
> Fixed home/end (they will move cursor to start/end of input), and blocked PG_UP/DOWN 

ok

> Added a version on helper title + more detailed info on "--help" switch (ncursesFM --help).

ok, nice

> Only issue remaining is that version is set to 2.2 instead of 3.0 (latest). I don't understand why, may be i tagged that release in a wrong way?

No, for me it gives 3.0

> You already can hide whatever you wish from latest line, have a look at ncursesFM.conf (last line): you can customize order/what to show of sysinfo line.

I know this file, but I cant do it. Perhaps due to  this : Only for systemd systems

Now, just a little problem concerning keyboard:
By default mode is insert, and hitting the first time Insert key, and the keyboard uses overwrite, but the message is : 'Enabled insert mode' which is wrong. Hitting Insert key again , and the state changes, but the message is wrong 'Disabled insert mode'

A+

**Comment by FedeDP** [comment] 2016-05-22 17:16
Fixed insert mode strings!
Mmmh so you have got 3.0, that's really weird. Well, at least it works fine :D

What do you mean by "only for systemd systems"? 
Thanks!

**Comment by JujuLand** [comment] 2016-05-22 18:25
I read it in /etc/ncursesFM.conf :

Not 0 to inhibits power management functions through sd-bus,
only while a list of job is running. Defaults to 0. Only for systemd systems.
inhibit = 1;

I found this:
sd-bus -> needed for powermanagement inhibition functions, devices/iso mount and packages installation.

But:
alain@Gramps-JujuLand:~$ sudo apt-get install libsystemd-dev 
...
E: Impossible to find libsystemd-dev packet
...

A+

**Comment by JujuLand** [comment] 2016-05-22 18:51
I found this on package.ubuntu.com:

Paquet libsystemd-dev

wily (libdevel): systemd utility library - development files 
225-1ubuntu9: amd64 arm64 armhf i386 powerpc ppc64el
wily-updates (libdevel): systemd utility library - development files 
225-1ubuntu9.1: amd64 arm64 armhf i386 powerpc ppc64el
xenial (libdevel): systemd utility library - development files 
229-4ubuntu4: amd64 arm64 armhf i386 powerpc ppc64el s390x
xenial-updates (libdevel): systemd utility library - development files 
229-4ubuntu5: amd64 arm64 armhf i386 powerpc ppc64el s390x
yakkety (libdevel): systemd utility library - development files 
229-6ubuntu1: amd64 arm64 armhf i386 powerpc ppc64el s390x

It doesn't exists for Precise (Ubuntu 12.04) :(

A+

**Comment by JujuLand** [comment] 2016-05-22 19:06
I have found a bad solution. I have modified the message to " "
    const char *ac_online = "On AC", *fail = " ";
I think it could be an option in ncursesFM to set the value of the string.
It will allow to mask it for Ubuntu  < 15.10 users

A+

**Comment by FedeDP** [comment] 2016-05-22 22:37
In image_previewer branch, ncursesFM.conf has an option to change "sysinfo line" layout, see here:
https://github.com/FedeDP/ncursesFM/blob/image_previewer/ncursesFM.conf#L45

You can customize it the way you wish, eg: date/clock on the right, or nothing at all if left empty, ie:
sysinfo_layout = ""
You can choose not to print an info, like, in your case:
sysinfo_layout = "CP" (so it won't print Battery info) or if you want it specular, 
sysinfo_layout = "C P" (with a middle space, so layout will be -> left clock, right processes/ram monitor).
Hope this is clear enough :)

**Comment by JujuLand** [comment] 2016-05-23 06:45
Yes, it's clear.

But trying it :
pull, checkout, make, ./ncursesFM

alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ ls -ail src/ui*
956022 -rw-rw-r-- 1 alain alain 43235 mai   23 08:37 src/ui_functions.c

All the values I tried (CP, C P, P C) => Date on the left and Battery on the right 
:(

A+

**Comment by FedeDP** [comment] 2016-05-23 08:56
It is written in README file(last line on master branch readme) :)
I know it is too long, and adding some wiki pages is in my TODO, to lighten readme and make informations easier to find.
Btw build with:  
$ make CONFDIR=./  
if you're willing to test conf file support without installing ncursesFM.

**Comment by JujuLand** [comment] 2016-05-23 13:16
Building like this doesn't solve the problem:
$ make CONFDIR=./
$ ./ncursesFM
and like this also:
$ make CONFDIR=/etc/default/
$ ncursesFM

A+

**Comment by FedeDP** [comment] 2016-05-23 16:31
Let's start from scratch: delete ncursesFM folder.
$ git clone https://github.com/FedeDP/ncursesFM.git
$ cd ncursesFM
$ git checkout image_previewer
$ make CONFDIR=./
$ nano ncursesFM.conf
Set "sysinfo_layout" value as you wish
$ ./ncursesFM

**Comment by JujuLand** [comment] 2016-05-24 19:09
I done exactly what you said, and it not good
When making, I saw this: 

alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ make CONFDIR=./
/bin/sh: 1: **test: -ge: unexpected operator**
**systemd support disabled, minimum required version 221**.
libX11 support enabled.
libcups support enabled.
libconfig support enabled.

A+

**Comment by FedeDP** [comment] 2016-05-25 14:09
Well, i tried right now building without libsystemd, and it worked.
In fact, systemd has nothing to do with that feature...this is really weird.
I used sysinfo_layout = "C P" , and this is the result: http://postimg.org/image/9i1p5768r/full/ .
Sorry if this question would sound pretty stupid, don't want to offend you, i'm only hoping to solve this issue... have you uncommented the "sysinfo_layout" line in ncursesFM.conf? This way:
http://dpaste.com/0H8N9YK

This is the last thing that comes to my mind.

**Comment by JujuLand** [comment] 2016-05-25 14:44
Here is the end my conf file:
**45 ## Sysinfo line layout
46 ## use:
47 ## C -> clock
48 ## P -> process/ram monitor
49 ## B -> battery monitor
50 sysinfo_layout = "C P"**   (no
[ncursesFM.conf.zip](https://github.com/FedeDP/ncursesFM/files/282220/ncursesFM.conf.zip)

 line after)

Display is always bad, and quitting, I saw an error:

**alain@Gramps-JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ ./ncursesFM
Config file: syntax error at line 51.**

If I add a line after "C P", the error indicates one line more:

**JujuLand:/opt/TuxPrograms/trunks/ncursesFM$ ./ncursesFM
Config file: syntax error at line 52.**

So I suppose, it's a bug reading the conf file, and not finding something ?

A+

**Comment by FedeDP** [comment] 2016-05-25 15:14
That's the issue...what libconfig version are you running?

**Comment by JujuLand** [comment] 2016-05-25 15:32
ii  libconfig-simple-perl                         4.59-5                                              simple configuration file class
ii  libconfig8                                    1.3.2-2ubuntu2                                      parsing and manipulation of structured configuration files
ii  libconfig8-dev                                1.3.2-2ubuntu2                                      parsing and manipulation of structured config files(development)

I use Ubuntu 12.04

A+

**Comment by FedeDP** [comment] 2016-05-25 22:14
It seems i'm an idiot indeed... i just pushed a small commit to image_previewer branch with that issue fixed.

**Comment by JujuLand** [comment] 2016-05-26 07:06
Well, now it works, but I don't understand something.
I use make 'CONFDIR=./' , set "C P", and 'sudo make install'
It works from any directory.
ok

But modifying default conffile doesn't change something in display
I then build using 'CONFDIR=/etc/default'
Same problem (:

Where do I fail ?

Could also it be viewable this setting in logfile ?

A+

**Comment by FedeDP** [comment] 2016-05-26 08:57
It works this way: if you use CONFDIR=$somedir, it will assume you have ncursesFM.conf installed in that place.  
This is only for testing purpose(like BINDIR=./) because it makes you try ncursesFM libconfig support even without installing.  
When you feel ready to install, you should only type same commands as every other project with a makefile:  
$ make
$ sudo make install 

PS: i will add some more info to the log file ;)

**Comment by JujuLand** [comment] 2016-05-26 12:04
ok, now all is ok.

No more error in the console, and the conf file is correctly read.
Just the few info perhaps missing in the log.

After, you just wil have to see lang support ;)

A+

**Comment by FedeDP** [comment] 2016-05-26 12:18
I'm gonna push the log improvements asap:)
You're a great tester btw, thanks for your time!

**Closed as completed** 2016-05-26 12:19 UTC
Labels: bug
